---
openapi: 3.1.0
info:
  title: User API
  description: This is the API of the User service
  contact:
    email: quentin.legoff44@gmail.com
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /:
    get:
      tags:
      - developers
      summary: home page of the service
      operationId: home
      responses:
        "200":
          description: welcome message
          content:
            text/html:
              schema:
                type: string
                example: <h1>Welcome to the User service!</h1>
  /user/{userId}:
    get:
      tags:
        - developers
      summary: get the user by his ID
      description: By passing in the appropriate options, you can get information about an user
      operationId: get_user_by_id
      parameters:
        - name: userid
          in: path
          description: User ID.
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: user
          content:
            application/json:
              schema:
                $ref: '#components/schemas/User'
        "400":
          description: bad input parameter
  /user/{userId}/reservations:
    get:
      tags:
        - developers
      summary: get the user's reservations
      description: By passing in the appropriate option, you can get information about user's reservations with movie information
      operationId: get_user_reservations_by_id
      parameters:
        - name: userid
          in: path
          description: User ID.
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: information about the user's reservation
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Reservations'
        "400":
          description: bad input parameter

components:
  schemas:
    User:
      required:
        - id
        - name
        - last_active
      type: object
      properties:
        id:
          type: string
          example: "chris_rivers"
        name:
          type: string
          example: "Chris Rivers"
        last_active:
          type: int
          example: 1360031010
    Reservations:
      type: object
      properties:
        userid:
          type: string
          example: "dwight_schrute"
        dates:
          type: array
          items:
            $ref: '#/components/schemas/DateReservationInfo'
    DateReservationInfo:
      type: object
      properties:
        date:
          type: string
          example: "20151201"
        movieData:
          type: array
          items:
            $ref: '#/components/schemas/Movie'
        movies:
          type: array
          items:
            type: string
            example: "7daf7208-be4d-4944-a3ae-c1c2f516f3e6"
    Movie:
      type: object
      properties:
        title:
          type: string
          example: The Martian
        rating:
          type: integer
          example: 7
        director:
          type: string
          example: Paul McGuigan
        id:
          type: string
          example: 39ab85e5-5e8e-4dc5-afea-65dc368bd7ab

