---
openapi: 3.1.0
info:
  title: User API
  description: This is the API of the User service
  contact:
    email: quentin.legoff44@gmail.com
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /:
    get:
      tags:
      - developers
      summary: home page of the service
      operationId: home
      responses:
        "200":
          description: welcome message
          content:
            text/html:
              schema:
                type: string
                example: <h1>Welcome to the User service!</h1>
  /users/{userId}:
    get:
      tags:
        - developers
      summary: get the user by his ID
      description: By passing in the appropriate options, you can get information about an user
      operationId: get_user_by_id
      parameters:
        - name: userid
          in: path
          description: User ID.
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: user
          content:
            application/json:
              schema:
                $ref: '#components/schemas/User'
        "400":
          description: bad input parameter
components:
  schemas:
    User:
      required:
        - id
        - name
        - last_active
      type: object
      properties:
        id:
          type: string
          example: "chris_rivers"
        name:
          type: string
          example: "Chris Rivers"
        last_active:
          type: int
          example: 1360031010

